FROM apache/airflow:2.7.3

# Install sudo to allow elevated permissions for the airflow user
USER root
RUN apt-get update && apt-get install -y sudo
# Install nano text editor using sudo
RUN sudo apt-get install -y nano

# Copy your requirements.txt into the container
COPY requirements.txt /tmp/requirements.txt

# Copy the dbt_project.yml file to the airflow user's home directory
COPY dbt_project.yml /opt/airflow/dbt_project.yml

USER airflow
# Install the Python packages listed in requirements.txt and DBT
RUN pip install --no-cache-dir -r /tmp/requirements.txt

# Set DBT_PROFILES_DIR environment variable
ENV DBT_PROFILES_DIR=/opt/airflow/dbt

# Switch back to the airflow user
USER airflow
