apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-config
data:
  AIRFLOW__CORE__EXECUTOR: SequentialExecutor
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://admin_user:admin_password@postgres:5432/staging_db
  AIRFLOW__WEBSERVER__SECRET_KEY: my_shared_secret_key
  DATABASE_URL: postgresql://admin_user:admin_password@postgres:5432/staging_db
  PYTHONPATH: /opt/airflow
  AIRFLOW__LOGGING__REMOTE_LOGGING: "False"

