apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
spec:
  type: NodePort
  selector:
    app: airflow-webserver
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
        - name: airflow-webserver
          image: airflow-webserver:local
          envFrom:
            - configMapRef:
                name: airflow-config
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: helpers
              mountPath: /opt/airflow/helpers
            - name: dbt
              mountPath: /opt/airflow/dbt
            - name: utils
              mountPath: /opt/airflow/utils
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs
          command: ["/bin/bash", "-c"]
          args:
            - >
              airflow db init &&
              airflow webserver &
              sleep 10 &&
              airflow users create --username admin --firstname Admin --lastname User --email admin@example.com --role Admin --password admin &&
              tail -f /dev/null
      volumes:
        - name: helpers
          hostPath:
            path: /data/helpers
            type: Directory
        - name: dbt
          hostPath:
            path: /data/dbt
            type: Directory
        - name: dags
          hostPath:
            path: /data/dags
            type: Directory
        - name: utils
          hostPath:
            path: /data/utils
            type: Directory
        - name: logs
          emptyDir: {}
